---
controller:
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "2.404"
  tagLabel: 2.404
  imagePullPolicy: "Always"
  imagePullSecretName:
  disableRememberMe: false
  numExecutors: 1
  # configures the executor mode of the Jenkins node. Possible values are: NORMAL or EXCLUSIVE
  executorMode: "NORMAL"
  # This is ignored if enableRawHtmlMarkupFormatter is true
  markupFormatter: plainText
  customJenkinsLabels: []
  # The default configuration uses this secret to configure an admin user
  # If you don't need that user or use a different security realm then you can disable it
  adminSecret: true
  hostNetworking: false
  # When enabling LDAP or another non-Jenkins identity source, the built-in admin account will no longer exist.
  # If you disable the non-Jenkins identity store and instead use the Jenkins internal one,
  # you should revert controller.adminUser to your preferred admin user:
  adminUser: "admin"
  # adminPassword: <defaults to random>
  admin:
    existingSecret: ""
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  installPlugins:
    - kubernetes:3923.v294a_d4250b_91
    - kubernetes-credentials:0.10.0
    - kubernetes-credentials-provider:1.211.vc236a_f5a_2f3c
    - kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
    - variant:59.vf075fe829ccb
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.0.1
    - configuration-as-code:1625.v27444588cc3d
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
          - id: "pat"
            name: "Pat"
            password: "changeme"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
rbac:
  readSecrets: true